FROM nvcr.io/nvidia/nemo:25.07

WORKDIR /workspace

RUN pip install --no-cache-dir \
    wandb \
    sentencepiece \
    tiktoken \
    datasets \
    transformers==4.51.0 \
    accelerate \
    omegaconf \
    modelscope